#name : try {...} catch(...) {...}
# --
try
{
    $0
}
catch (${1:zt::exception& e})
{
	zwarn << __FUNCTION__ << "() -- " << e.what() << endl;
}